---
- name: Download kernel packages
  get_url: "url={{ item.url }} dest={{ item.dest }}"
  with_items: "{{ kernel_packages }}"

- name: Install kernel packages
  apt: "pkg={{ kernel_packages | json_query('[*].dest') }} "

- name: Update grub
  shell: update-grub

- name: Reboot
  shell: reboot
  async: 0
  poll: 0

- name: Waiting for server come back
  local_action: >
    wait_for host="{{ ansible_ssh_host | default(inventory_hostname) }}"
    state=started port=22 delay=30 timeout=600 connect_timeout=15
